"use client";

import { useEffect, useState } from "react";

type Artifact = {
  id: string;
  kind: "preview" | "blend" | "export" | "log";
  filename: string;
  content_type: string;
  checksum_sha256: string;
  size_bytes: number;
};

type JobResponse = {
  job: {
    id: string;
    status: string;
    task: string;
    result_summary?: string | null;
    error_message?: string | null;
    attempt_count: number;
    operation_results?: unknown;
  };
  artifacts: Artifact[];
  review: {
    decision: string;
    notes: string;
    reviewer_user_id: string;
    reviewed_at: string;
  } | null;
};

export default function ReviewConsole({ jobId }: { jobId: string }) {
  const [token, setToken] = useState("");
  const [notes, setNotes] = useState("");
  const [data, setData] = useState<JobResponse | null>(null);
  const [previewUrl, setPreviewUrl] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    return () => {
      if (previewUrl) URL.revokeObjectURL(previewUrl);
    };
  }, [previewUrl]);

  async function load() {
    setBusy(true);
    setMessage("");
    try {
      const response = await fetch(`/api/cloud/jobs/${jobId}`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
        cache: "no-store",
      });
      const payload = (await response.json()) as JobResponse & { error?: string };
      if (!response.ok) throw new Error(payload.error ?? "Could not load job");
      setData(payload);
      const preview = payload.artifacts.find((artifact) => artifact.kind === "preview");
      if (preview) {
        const imageResponse = await fetch(`/api/cloud/artifacts/${preview.id}`, {
          headers: token ? { Authorization: `Bearer ${token}` } : {},
          cache: "no-store",
        });
        if (imageResponse.ok) {
          const blob = await imageResponse.blob();
          if (previewUrl) URL.revokeObjectURL(previewUrl);
          setPreviewUrl(URL.createObjectURL(blob));
        }
      }
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Could not load review");
    } finally {
      setBusy(false);
    }
  }

  async function decide(decision: "approved" | "rejected" | "changes_requested") {
    setBusy(true);
    setMessage("");
    try {
      const response = await fetch(`/api/cloud/jobs/${jobId}/review`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ decision, notes }),
      });
      const payload = (await response.json()) as {
        error?: string;
        versionNumber?: number;
      };
      if (!response.ok) throw new Error(payload.error ?? "Review failed");
      setMessage(
        decision === "approved" && payload.versionNumber
          ? `Approved and published as asset version v${payload.versionNumber}.`
          : `Decision saved: ${decision}.`,
      );
      await load();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Review failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="reviewGrid">
      <article className="panel reviewPreview">
        <span className="panelLabel">BLENDER PREVIEW</span>
        {previewUrl ? (
          <img src={previewUrl} alt="Blender render generated by the Device Agent for review" />
        ) : (
          <div className="reviewPlaceholder">
            <strong>No preview loaded</strong>
            <p>Enter your private member token and load this job.</p>
          </div>
        )}
      </article>

      <article className="panel reviewDetails">
        <span className="panelLabel">JOB {jobId}</span>
        <label>
          Member / owner token
          <input
            type="password"
            autoComplete="off"
            value={token}
            onChange={(event) => setToken(event.target.value)}
            placeholder="nfu_..."
          />
        </label>
        <button className="secondaryButton" disabled={busy || !token} onClick={load}>
          {busy ? "Loading…" : "Load job"}
        </button>

        {data ? (
          <div className="reviewMeta">
            <div><span>Status</span><strong>{data.job.status}</strong></div>
            <div><span>Attempts</span><strong>{data.job.attempt_count}</strong></div>
            <p>{data.job.task}</p>
            {data.job.result_summary ? <p>{data.job.result_summary}</p> : null}
            <div className="artifactList">
              {data.artifacts.map((artifact) => (
                <span key={artifact.id}>
                  {artifact.kind} · {artifact.filename} · {Math.ceil(artifact.size_bytes / 1024)} KB
                </span>
              ))}
            </div>
          </div>
        ) : null}

        <label>
          Review notes
          <textarea rows={5} value={notes} onChange={(event) => setNotes(event.target.value)} />
        </label>
        <div className="reviewActions">
          <button disabled={busy || data?.job.status !== "awaiting_approval"} onClick={() => decide("approved")}>
            Approve & publish
          </button>
          <button disabled={busy || data?.job.status !== "awaiting_approval"} onClick={() => decide("changes_requested")}>
            Request changes
          </button>
          <button disabled={busy || data?.job.status !== "awaiting_approval"} onClick={() => decide("rejected")}>
            Reject
          </button>
        </div>
        {message ? <p className="reviewMessage">{message}</p> : null}
      </article>
    </section>
  );
}
